### ISSUE TITLE
DBtroopes setup

### ISSUE THREAD

**Issue by olabknbit** [olabknbit/imdb-webpage-improvement#4]
Completing instructions from `README` does not provide a working solution. After running the script I get an error:
```
Traceback (most recent call last):
  File "/Users/aleksandra/PycharmProjects/SPD/web_scrapper.py", line 161, in <module>
    main()
  File "/Users/aleksandra/PycharmProjects/SPD/web_scrapper.py", line 157, in main
    improve_webpage(url)
  File "/Users/aleksandra/PycharmProjects/SPD/web_scrapper.py", line 134, in improve_webpage
    add_tropes_info(soup, series_name)
  File "/Users/aleksandra/PycharmProjects/SPD/web_scrapper.py", line 20, in add_tropes_info
    tropes = retrieve_tropes(series_name)
  File "/Users/aleksandra/PycharmProjects/SPD/query_dbtropes.py", line 20, in retrieve_tropes
    g.parse("series_data.nt", format="nt")
  File "/Users/aleksandra/PycharmProjects/SPD/venv/lib/python3.8/site-packages/rdflib/graph.py", line 1032, in parse
    source = create_input_source(source=source, publicID=publicID,
  File "/Users/aleksandra/PycharmProjects/SPD/venv/lib/python3.8/site-packages/rdflib/parser.py", line 184, in create_input_source
    file = open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/aleksandra/PycharmProjects/SPD/series_data.nt'
```

Possible solution: upload an automated script that creates `series_data.nt` from `dbtroopes.nt`.

**Comment by bulkaaa** [comment]
@olabknbit script was created, but it was left to be uncommented (probably unintuitive). 
Moved it to setup.py and added instructions to run setup.py in README

**Comment by bulkaaa** [comment]
Fix here: https://github.com/olabknbit/imdb-webpage-improvement/pull/6
